### ISSUE TITLE
Improve implementation section for awesome-ios

### ISSUE THREAD

**Issue by lfarah** [opentok/accelerator-core-ios#14]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/opentok/accelerator-core-ios/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-ios/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## Question or Feature Request

The only problem I found was the ```README.md```, which lacks an ```Example Section```
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to easily create an ```Example Section```
The only implementation example I found was on how to run the example app, but not actual example code was shown on the README

What are your thoughts? 😄

**Comment by lfarah** [comment]
Please take a look at this before I can [approve your PR](https://github.com/vsouza/awesome-ios/pull/1443)

**Comment by Lucashuang0802** [comment]
Hi @lfarah. Yes, we just released this missing piece and already merged the code into `dev`. How do you think that: https://github.com/opentok/accelerator-core-ios/tree/dev#sample-codes?

**Comment by lfarah** [comment]
Perfect!
