### ISSUE TITLE
AppDelegate Crashing for iOS 13 Devices. 

### ISSUE THREAD

**Issue by mugabi0978** [opentok/accelerator-core-ios#49]
This source crashes on running on iOS 13 devices.

This crash is in appdelegate file.

Please test, and provide an update on how to resolve this.

**Comment by rktalusani** [comment]
please update the podfile to use Opentok version 2.16.3 instead of 2.16.1. This should fix the issue,

**Comment by rktalusani** [comment]
you may want to upgrade to 2.16.5 as that is the latest version

**Comment by mugabi0978** [comment]
> you may want to upgrade to 2.16.5 as that is the latest version

Thanks i already did that though i need these people to ugrade and release a version on cocoapods to reflect this

**Comment by rktalusani** [comment]
@msach22

**Comment by mugabi0978** [comment]
> @msach22

Can this https://cocoapods.org/pods/OTAcceleratorCore be updated to use latest opentok sdk (2.16.5) ?

**Comment by msach22** [comment]
Thanks for reporting. We're looking at fixing this issue. Unfortunately, I don't have an ETA, but we are tracking this internally and will fix as soon as we can.

**Comment by jtiet** [comment]
@mugabi0978 The AcceleratorCore has been updated to use OpenTok SDK v2.16.5.

**Comment by mugabi0978** [comment]
@msach22 @jtiet @rktalusani Thanks for the Update and FollowUp. All the Best.
